--QUERY NO. 5 (CHOSEN PRODUCT: TABLE, WITH ID = 1)

USE [TaskNo2]
GO

SELECT COUNT(T.TRANSPORT_ID) AS NUMBER_OF_ORDERS
FROM [TRANSPORTS] T
JOIN [LOCATIONS] L1 ON L1.LOCATION_ID = T.SOURCE_ID
JOIN [LOCATIONS] L2 ON L2.LOCATION_ID = T.TARGET_ID
WHERE L1.COUNTRY_ID <> L2.COUNTRY_ID
AND T.TRANSPORT_ID NOT IN (
	SELECT TT.TRANSPORT_ID
	FROM [TRANSPORTS] TT
	JOIN [TRS-PRO] TP ON TP.TRANSPORT_ID = TT.TRANSPORT_ID
	WHERE TP.PRODUCT_ID = 1
	GROUP BY TT.TRANSPORT_ID
)