-- QUERY NO. 3

USE [TaskNo2]
GO

SELECT TE.EMPLOYEE_ID, E.EMPLOYEE_NAME
FROM [TRS-EMP] TE
JOIN [EMPLOYEES] E ON E.EMPLOYEE_ID = TE.EMPLOYEE_ID
JOIN [TRS-VEH] TV ON TV.TRANSPORT_ID = TE.TRANSPORT_ID AND TV.VIN = TE.VIN
GROUP BY TE.EMPLOYEE_ID, E.EMPLOYEE_NAME
HAVING SUM(DATEDIFF(SECOND, TV.DRIVE_LAUNCH, TV.DRIVE_FINISH)) >= 1.5 * (
	SELECT SUM(DATEDIFF(SECOND, TVV.DRIVE_LAUNCH, TVV.DRIVE_FINISH)) / COUNT(DISTINCT EE.EMPLOYEE_ID)
	FROM [EMPLOYEES] EE
	LEFT JOIN [TRS-EMP] TEE ON TEE.EMPLOYEE_ID = EE.EMPLOYEE_ID
	LEFT JOIN [TRS-VEH] TVV ON TVV.TRANSPORT_ID = TEE.TRANSPORT_ID AND TVV.VIN = TEE.VIN
)
ORDER BY SUM(DATEDIFF(SECOND, TV.DRIVE_LAUNCH, TV.DRIVE_FINISH)) DESC