-- QUERY NO. 2

USE [TaskNo2]
GO

SELECT C.CUSTOMER_ID, C.CUSTOMER_NAME, T.TRANSPORT_ID, SUM(V.DISTANCE) AS DISTANCE
FROM [CUSTOMERS] C
JOIN [TRANSPORTS] T ON T.CUSTOMER_ID = C.CUSTOMER_ID
JOIN [TRS-VEH] V ON V.TRANSPORT_ID = T.TRANSPORT_ID
WHERE T.TRANSPORT_ID IN (
	SELECT TOP 15 TT.TRANSPORT_ID
	FROM [TRANSPORTS] TT
	JOIN [CUSTOMERS] CC ON CC.CUSTOMER_ID = TT.CUSTOMER_ID
	JOIN [TRS-VEH] TV ON TV.TRANSPORT_ID = TT.TRANSPORT_ID
	WHERE C.CUSTOMER_ID = CC.CUSTOMER_ID
	GROUP BY TT.TRANSPORT_ID--, SUM(TV.DISTANCE)
	HAVING COUNT(TV.TRANSPORT_ID) >= 2
	ORDER BY SUM(TV.DISTANCE) DESC
)
GROUP BY C.CUSTOMER_ID, C.CUSTOMER_NAME, T.TRANSPORT_ID
ORDER BY C.CUSTOMER_ID ASC, SUM(V.DISTANCE) DESC