-- QUERY NO. 1

USE [TaskNo2]
GO

SELECT CAST(T.PICKUP_TIME AS DATE) AS PICKUP_DAY, C.COUNTRY_NAME, SUM(TP.AMOUNT * P.VOLUME) AS SUM_OF_VOLUME
FROM [TRANSPORTS] T
JOIN [TRS-PRO] TP ON T.TRANSPORT_ID = TP.TRANSPORT_ID
JOIN [PRODUCTS] P ON P.PRODUCT_ID = TP.PRODUCT_ID
JOIN [LOCATIONS] L ON L.LOCATION_ID = T.SOURCE_ID
JOIN [COUNTRIES] C ON C.COUNTRY_ID = L.COUNTRY_ID
GROUP BY CAST(T.PICKUP_TIME AS DATE), T.SOURCE_ID, C.COUNTRY_NAME
ORDER BY CAST(T.PICKUP_TIME AS DATE) ASC