-- UPDATE NO. 1

USE [TaskNo2]
GO

SET TRANSACTION
ISOLATION LEVEL READ COMMITTED

BEGIN TRANSACTION

UPDATE [COUNTRIES]
SET COUNTRY_NAME = 'North Macedonia'
WHERE COUNTRY_NAME = 'Macedonia'

COMMIT